ens_jobeet_homepage:
    path:     /
    defaults: { _controller: EnsJobeetBundle:Default:index }

ens_jobeet_main:
    resource: "@EnsJobeetBundle/Resources/config/routing/main.yml"
    prefix:   /main

ens_jobeet_estabelecimento:
    resource: "@EnsJobeetBundle/Resources/config/routing/estabelecimento.yml"
    prefix:   /estabelecimento

ens_jobeet_comentario:
    resource: "@EnsJobeetBundle/Resources/config/routing/comentario.yml"
    prefix:   /comentario

ens_jobeet_evento:
    resource: "@EnsJobeetBundle/Resources/config/routing/evento.yml"
    prefix:   /evento

ens_jobeet_comentario_evento:
        resource: "@EnsJobeetBundle/Resources/config/routing/comentario_evento.yml"
        prefix:   /comentario_evento

