ens_jobeet_job:
    resource: "@EnsJobeetBundle/Controller/JobController.php"
    type:     annotation

ens_jobeet_lucky:
    resource: "@EnsJobeetBundle/Controller/LuckyController.php"
    type:     annotation

ens_jobeet:
    resource: "@EnsJobeetBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
