Ens\JobeetBundle\Entity\Estabelecimento:
  type: entity
  table: estabelecimento
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    nome_estabelecimento:
      type: string
      length: 255

    tipo_estabelecimento:
      type: string
      length: 255

    endereco:
      type: string
      length: 255

    cidade:
      type: string
      length: 255

    email:
      type: string
      length: 255
      nullable: true

    cnpj:
      type: string
      length: 255
      nullable: true

    telefone:
      type: string
      length: 255

    url_img:
      type: string
      length: 255

    descricao:
      type: text

  oneToMany:
    evento:
      targetEntity: Evento
      mappedBy: estabelecimentos
    comentario:
      targetEntity: Comentario
      mappedBy: estabelecimentos
