comentario_index:
    path:     /
    defaults: { _controller: "EnsJobeetBundle:Comentario:index" }
    methods:  GET

comentario_show:
    path:     /{id}/show
    defaults: { _controller: "EnsJobeetBundle:Comentario:show" }
    methods:  GET

comentario_new:
    path:     /new
    defaults: { _controller: "EnsJobeetBundle:Comentario:new" }
    methods:  [GET, POST]

comentario_edit:
    path:     /{id}/edit
    defaults: { _controller: "EnsJobeetBundle:Comentario:edit" }
    methods:  [GET, POST]

comentario_delete:
    path:     /{id}/delete
    defaults: { _controller: "EnsJobeetBundle:Comentario:delete" }
    methods:  DELETE
