comentario_evento_index:
    path:     /
    defaults: { _controller: "EnsJobeetBundle:Comentario_Evento:index" }
    methods:  GET

comentario_evento_show:
    path:     /{id}/show
    defaults: { _controller: "EnsJobeetBundle:Comentario_Evento:show" }
    methods:  GET

comentario_evento_new:
    path:     /new
    defaults: { _controller: "EnsJobeetBundle:Comentario_Evento:new" }
    methods:  [GET, POST]

comentario_evento_edit:
    path:     /{id}/edit
    defaults: { _controller: "EnsJobeetBundle:Comentario_Evento:edit" }
    methods:  [GET, POST]

comentario_evento_delete:
    path:     /{id}/delete
    defaults: { _controller: "EnsJobeetBundle:Comentario_Evento:delete" }
    methods:  DELETE
